// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi0xh3s2KjXodJD7Y0ieOH1j22NGNIOEM',
    appId: '1:549975673229:web:6e15b248f8837d879d95c4',
    messagingSenderId: '549975673229',
    projectId: 'study-app-4313c',
    authDomain: 'study-app-4313c.firebaseapp.com',
    storageBucket: 'study-app-4313c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJkyMLgY_e5trTNLCc44tRFO1dRjN6Mwo',
    appId: '1:549975673229:android:a45224ad8b4718cf9d95c4',
    messagingSenderId: '549975673229',
    projectId: 'study-app-4313c',
    storageBucket: 'study-app-4313c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGY6oGJUAKkaGfNnDADPqC3gNIIBhj68Q',
    appId: '1:549975673229:ios:efa59e05461a7d129d95c4',
    messagingSenderId: '549975673229',
    projectId: 'study-app-4313c',
    storageBucket: 'study-app-4313c.appspot.com',
    iosClientId: '549975673229-cud9mk0oj4thsdbvhibk628i0n22hrcv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStudyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGY6oGJUAKkaGfNnDADPqC3gNIIBhj68Q',
    appId: '1:549975673229:ios:efa59e05461a7d129d95c4',
    messagingSenderId: '549975673229',
    projectId: 'study-app-4313c',
    storageBucket: 'study-app-4313c.appspot.com',
    iosClientId: '549975673229-cud9mk0oj4thsdbvhibk628i0n22hrcv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStudyApp',
  );
}
